name: AI Code Review and Security Audit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-security-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/scripts/requirements.txt ]; then pip install -r .github/scripts/requirements.txt; fi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          json: true

      - name: Run AI Security Audit
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python .github/scripts/code_review.py '${{ steps.changed-files.outputs.all_changed_files }}' '${{ github.event.pull_request.number }}'
